runtime: java
env: flex

env_variables:
   GOOGLE_CLOUD_PROJECT: truethat-app
   APPLICATION_NAME: TrueThat Backend

handlers:
- url: /.*
  script: this field is required, but ignored

runtime_config:  # Optional
  jdk: openjdk8
  server: jetty9

manual_scaling:
  instances: 1