runtime: java
env: flex

env_variables:
   __GCLOUD_PROJECT__: truethat-app
   APPLICATION_NAME: TrueThat Backend Production
   STUDIO_BUCKET: truethat-studio
   DATASTORE_SERVICE_ACCOUNT: truethat-app@appspot.gserviceaccount.com
   DATASTORE_USE_PROJECT_ID_AS_APP_ID: true

# Leveraging Jetty 9 & Servlet 3.1 @WebServlet annotation
handlers:
- url: /.*
  script: this field is required, but ignored

runtime_config:
  jdk: openjdk8
  server: jetty9

beta_settings:
  java_quickstart: true

manual_scaling:
  instances: 1