runtime: java
env: flex

env_variables:
   GOOGLE_CLOUD_PROJECT: truethat-app
   APPLICATION_NAME: TrueThat Backend Production

handlers:
- url: /.*
  script: this field is required, but ignored

runtime_config:
  jdk: openjdk8
  server: jetty9

# Leveraging Jetty 9 & Servlet 3.1 @WebServlet annotation
beta_settings:
  java_quickstart: true

manual_scaling:
  instances: 1